### ISSUE TITLE
Figure out what the API should look like

### ISSUE THREAD

**Issue by ben-cunningham** [ben-cunningham/pybot#17]
@ahendy0 What do you think the API should look like for the bot. I'm starting to lean towards it being built on top of web server now, I think that makes more sense. You should check out the Flask documentation, it could be something similar to that... http://flask.pocoo.org

```
bot = Bot(<token>)
bot.set_greeting('hello! Welcome to this place')

@bot.recieve('/song')
def auth(message):
	bot.send_message('')
	bot.send_message('')

@bot.recieve('/queue')
def queue(song):
	bot.send_message('')

if __name__ == "__main__":
	bot.start()
```

**Comment by ben-cunningham** [comment]
Or maybe it shouldn't actually... I have no idea

**Comment by ahendy0** [comment]
Nah peoeple define their own server and integrate the bot stuff as above... unless I am confused.
the decorators will be user side not us side

**Comment by ben-cunningham** [comment]
@ahendy0 the example i posted was what it could be like if we had a server built in, similar to flask.

**Comment by ahendy0** [comment]
oh im not sure then

**Comment by ben-cunningham** [comment]
@ahendy0 It would be a nice way to do it but maybe that's out of scope, i'm not really sure either

**Comment by ahendy0** [comment]
unless bot subclasses Flask

**Comment by ahendy0** [comment]
@ben-cunningham

**Comment by ben-cunningham** [comment]
Hmm yeah maybe like one of the properties is a flask server? Not too sure how that would work but yeah could be something along those lines.

**Comment by ahendy0** [comment]
intrasting

**Comment by ben-cunningham** [comment]
@ahendy0 

```
from fbmsgbot import Bot

bot = Bot(<API_TOKEN>)

def is_correct_song(payload):
	if payload.text == 'YES':
		# get the user and song they want
		# then queue up that song
		if success:
			return Message("Song added to playlist")
		else:
			return Message("Song could not be added. Please try again in a bit")
	if payload.text == 'NO':
		# Get new song or ask
		# the user to send a new query
		return Message('Sorry about that')


def webhook(message):
	if message.text:
		# would parse message for whatever
		# text we wanted, ie the whole string 
		# being a song request
		yes_button = Button("YES", payload=True)
		no_button = Button("NO", payload=False)
		return StructuredMessage("Is this the correct song?", [yes_button, no_button])

	# Option to return a basic string for a TextMessage,
	# Or can return a more complex StructuredMessage if they want
	return Message("Is this the song you would like added?", [Button('yes'), Button('No')])

if __main__:
	bot.register_webhook('/', webhook)
	bot.run()
```

As per what I said in Slack, this is just a rough idea of what it could look like if we build the bot on top of a web server, I'm kind of leaning towards this now
